const catData = [
  {
    breeds: [],
    categories: [
      {
        id: 2,
        name: "space",
      },
    ],
    id: "4v",
    url: "https://cdn2.thecatapi.com/images/4v.jpg",
    width: 487,
    height: 500,
  },
  {
    breeds: [],
    id: "mp",
    url: "https://cdn2.thecatapi.com/images/mp.jpg",
    width: 467,
    height: 700,
  },
  {
    breeds: [],
    categories: [
      {
        id: 3,
        name: "funny",
      },
    ],
    id: "14i",
    url: "https://cdn2.thecatapi.com/images/14i.gif",
    width: 264,
    height: 199,
  },
  {
    breeds: [],
    id: "1dp",
    url: "https://cdn2.thecatapi.com/images/1dp.jpg",
    width: 612,
    height: 612,
  },
  {
    breeds: [],
    id: "2ck",
    url: "https://cdn2.thecatapi.com/images/2ck.jpg",
    width: 500,
    height: 333,
  },
  {
    breeds: [],
    categories: [
      {
        id: 1,
        name: "hats",
      },
    ],
    id: "373",
    url: "https://cdn2.thecatapi.com/images/373.jpg",
    width: 2256,
    height: 1504,
  },
  {
    breeds: [],
    id: "44j",
    url: "https://cdn2.thecatapi.com/images/44j.jpg",
    width: 500,
    height: 333,
  },
  {
    breeds: [],
    id: "4s8",
    url: "https://cdn2.thecatapi.com/images/4s8.jpg",
    width: 480,
    height: 359,
  },
  {
    breeds: [],
    id: "57r",
    url: "https://cdn2.thecatapi.com/images/57r.jpg",
    width: 600,
    height: 800,
  },
  {
    breeds: [],
    categories: [
      {
        id: 2,
        name: "space",
      },
    ],
    id: "5d4",
    url: "https://cdn2.thecatapi.com/images/5d4.jpg",
    width: 706,
    height: 500,
  },
  {
    breeds: [],
    categories: [
      {
        id: 2,
        name: "space",
      },
    ],
    id: "5gv",
    url: "https://cdn2.thecatapi.com/images/5gv.jpg",
    width: 500,
    height: 375,
  },
  {
    breeds: [],
    id: "70v",
    url: "https://cdn2.thecatapi.com/images/70v.jpg",
    width: 1024,
    height: 683,
  },
  {
    breeds: [],
    categories: [
      {
        id: 1,
        name: "hats",
      },
    ],
    id: "7g4",
    url: "https://cdn2.thecatapi.com/images/7g4.jpg",
    width: 400,
    height: 521,
  },
  {
    breeds: [],
    id: "7m3",
    url: "https://cdn2.thecatapi.com/images/7m3.gif",
    width: 500,
    height: 281,
  },
  {
    breeds: [],
    id: "8jc",
    url: "https://cdn2.thecatapi.com/images/8jc.jpg",
    width: 1280,
    height: 960,
  },
  {
    breeds: [],
    id: "8kk",
    url: "https://cdn2.thecatapi.com/images/8kk.jpg",
    width: 500,
    height: 369,
  },
  {
    breeds: [],
    id: "9i4",
    url: "https://cdn2.thecatapi.com/images/9i4.jpg",
    width: 420,
    height: 590,
  },
  {
    breeds: [],
    id: "9l8",
    url: "https://cdn2.thecatapi.com/images/9l8.jpg",
    width: 680,
    height: 1024,
  },
  {
    breeds: [],
    id: "a1n",
    url: "https://cdn2.thecatapi.com/images/a1n.gif",
    width: 400,
    height: 224,
  },
  {
    breeds: [],
    id: "a7o",
    url: "https://cdn2.thecatapi.com/images/a7o.jpg",
    width: 533,
    height: 800,
  },
  {
    breeds: [],
    id: "acu",
    url: "https://cdn2.thecatapi.com/images/acu.jpg",
    width: 1000,
    height: 664,
  },
  {
    breeds: [],
    id: "ajo",
    url: "https://cdn2.thecatapi.com/images/ajo.gif",
    width: 300,
    height: 289,
  },
  {
    breeds: [],
    id: "aph",
    url: "https://cdn2.thecatapi.com/images/aph.jpg",
    width: 720,
    height: 960,
  },
  {
    breeds: [],
    id: "ar8",
    url: "https://cdn2.thecatapi.com/images/ar8.jpg",
    width: 580,
    height: 483,
  },
  {
    breeds: [],
    id: "b3a",
    url: "https://cdn2.thecatapi.com/images/b3a.jpg",
    width: 428,
    height: 644,
  },
  {
    breeds: [],
    id: "bno",
    url: "https://cdn2.thecatapi.com/images/bno.jpg",
    width: 375,
    height: 500,
  },
  {
    breeds: [],
    id: "bo4",
    url: "https://cdn2.thecatapi.com/images/bo4.jpg",
    width: 1200,
    height: 800,
  },
  {
    breeds: [],
    id: "cfc",
    url: "https://cdn2.thecatapi.com/images/cfc.jpg",
    width: 560,
    height: 384,
  },
  {
    breeds: [],
    id: "d29",
    url: "https://cdn2.thecatapi.com/images/d29.jpg",
    width: 1200,
    height: 1600,
  },
  {
    breeds: [],
    id: "d32",
    url: "https://cdn2.thecatapi.com/images/d32.png",
    width: 765,
    height: 1024,
  },
  {
    breeds: [],
    id: "d89",
    url: "https://cdn2.thecatapi.com/images/d89.jpg",
    width: 2592,
    height: 1728,
  },
  {
    breeds: [],
    id: "drp",
    url: "https://cdn2.thecatapi.com/images/drp.jpg",
    width: 499,
    height: 665,
  },
  {
    breeds: [],
    id: "e8p",
    url: "https://cdn2.thecatapi.com/images/e8p.png",
    width: 638,
    height: 482,
  },
  {
    breeds: [],
    id: "MTUxODAyOQ",
    url: "https://cdn2.thecatapi.com/images/MTUxODAyOQ.jpg",
    width: 900,
    height: 644,
  },
  {
    breeds: [],
    id: "MTYzMzQ3NQ",
    url: "https://cdn2.thecatapi.com/images/MTYzMzQ3NQ.jpg",
    width: 610,
    height: 575,
  },
  {
    breeds: [],
    id: "MTY5NDczNA",
    url: "https://cdn2.thecatapi.com/images/MTY5NDczNA.jpg",
    width: 500,
    height: 335,
  },
  {
    breeds: [],
    id: "MTY5NzI5NQ",
    url: "https://cdn2.thecatapi.com/images/MTY5NzI5NQ.jpg",
    width: 500,
    height: 333,
  },
  {
    breeds: [],
    id: "MTcyMTg2Ng",
    url: "https://cdn2.thecatapi.com/images/MTcyMTg2Ng.jpg",
    width: 467,
    height: 700,
  },
  {
    breeds: [],
    categories: [
      {
        id: 15,
        name: "clothes",
      },
    ],
    id: "MTgwMDcwNg",
    url: "https://cdn2.thecatapi.com/images/MTgwMDcwNg.jpg",
    width: 1600,
    height: 1200,
  },
  {
    breeds: [],
    id: "MTgyNTkyNw",
    url: "https://cdn2.thecatapi.com/images/MTgyNTkyNw.jpg",
    width: 768,
    height: 1024,
  },
  {
    breeds: [],
    id: "MTg1ODAwMg",
    url: "https://cdn2.thecatapi.com/images/MTg1ODAwMg.jpg",
    width: 1995,
    height: 2000,
  },
  {
    breeds: [],
    id: "MTg3Nzk5MQ",
    url: "https://cdn2.thecatapi.com/images/MTg3Nzk5MQ.jpg",
    width: 500,
    height: 375,
  },
  {
    breeds: [],
    id: "MTg4MjgxNA",
    url: "https://cdn2.thecatapi.com/images/MTg4MjgxNA.jpg",
    width: 828,
    height: 641,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "8 - 13",
          metric: "4 - 6",
        },
        id: "cymr",
        name: "Cymric",
        vetstreet_url: "http://www.vetstreet.com/cats/cymric",
        temperament: "Gentle, Loyal, Intelligent, Playful",
        origin: "Canada",
        country_codes: "CA",
        country_code: "CA",
        description:
          "The Cymric is a placid, sweet cat. They do not get too upset about anything that happens in their world. They are loving companions and adore people. They are smart and dexterous, capable of using his paws to get into cabinets or to open doors.",
        life_span: "8 - 14",
        indoor: 0,
        lap: 1,
        alt_names: "Spangle",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 3,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 5,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 1,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Cymric_(cat)",
        hypoallergenic: 0,
        reference_image_id: "3dbtapCWM",
      },
    ],
    id: "CKVhCI0bz",
    url: "https://cdn2.thecatapi.com/images/CKVhCI0bz.jpg",
    width: 1280,
    height: 720,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "5 - 10",
          metric: "2 - 5",
        },
        id: "java",
        name: "Javanese",
        vetstreet_url: "http://www.vetstreet.com/cats/javanese",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/javanese",
        temperament: "Active, Devoted, Intelligent, Playful",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "Javanese are endlessly interested, intelligent and active. They tend to enjoy jumping to great heights, playing with fishing pole-type or other interactive toys and just generally investigating their surroundings. He will attempt to copy things you do, such as opening doors or drawers.",
        life_span: "10 - 12",
        indoor: 0,
        alt_names: " ",
        adaptability: 4,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 4,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 2,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Javanese_cat",
        hypoallergenic: 1,
        reference_image_id: "xoI_EpOKe",
      },
    ],
    id: "V00qLe4Gw",
    url: "https://cdn2.thecatapi.com/images/V00qLe4Gw.jpg",
    width: 1920,
    height: 1280,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "5 - 9",
          metric: "2 - 4",
        },
        id: "munc",
        name: "Munchkin",
        vetstreet_url: "http://www.vetstreet.com/cats/munchkin",
        temperament: "Agile, Easy Going, Intelligent, Playful",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "The Munchkin is an outgoing cat who enjoys being handled. She has lots of energy and is faster and more agile than she looks. The shortness of their legs does not seem to interfere with their running and leaping abilities.",
        life_span: "10 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 2,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 1,
        wikipedia_url: "https://en.wikipedia.org/wiki/Munchkin_(cat)",
        hypoallergenic: 0,
        reference_image_id: "j5cVSqLer",
      },
    ],
    id: "mZZzMlywy",
    url: "https://cdn2.thecatapi.com/images/mZZzMlywy.jpg",
    width: 950,
    height: 950,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "8 - 16",
          metric: "4 - 7",
        },
        id: "norw",
        name: "Norwegian Forest Cat",
        cfa_url: "http://cfa.org/Breeds/BreedsKthruR/NorwegianForestCat.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/norwegian-forest-cat",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/norwegian-forest-cat",
        temperament:
          "Sweet, Active, Intelligent, Social, Playful, Lively, Curious",
        origin: "Norway",
        country_codes: "NO",
        country_code: "NO",
        description:
          "The Norwegian Forest Cat is a sweet, loving cat. She appreciates praise and loves to interact with her parent. She makes a loving companion and bonds with her parents once she accepts them for her own. She is still a hunter at heart. She loves to chase toys as if they are real. She is territorial and patrols several times each day to make certain that all is fine.",
        life_span: "12 - 16",
        indoor: 0,
        alt_names:
          "Skogkatt / Skaukatt, Norsk Skogkatt / Norsk Skaukatt, Weegie",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 3,
        intelligence: 4,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Norwegian_Forest_Cat",
        hypoallergenic: 0,
        reference_image_id: "06dgGmEOV",
      },
    ],
    id: "JnD5BF9Uq",
    url: "https://cdn2.thecatapi.com/images/JnD5BF9Uq.jpg",
    width: 1200,
    height: 800,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "5 - 11",
          metric: "2 - 5",
        },
        id: "sfol",
        name: "Scottish Fold",
        cfa_url: "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
        vetstreet_url:
          "http://www.vetstreet.com/cats/scottish-fold-highland-fold",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold",
        temperament:
          "Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving",
        origin: "United Kingdom",
        country_codes: "GB",
        country_code: "GB",
        description:
          'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
        life_span: "11 - 14",
        indoor: 0,
        alt_names: "Scot Fold",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 1,
        health_issues: 4,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Scottish_Fold",
        hypoallergenic: 0,
        reference_image_id: "o9t0LDcsa",
      },
    ],
    id: "JVITS8pXF",
    url: "https://cdn2.thecatapi.com/images/JVITS8pXF.jpg",
    width: 1080,
    height: 1160,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "8 - 16",
          metric: "4 - 7",
        },
        id: "sibe",
        name: "Siberian",
        cfa_url: "http://cfa.org/Breeds/BreedsSthruT/Siberian.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/siberian",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/siberian",
        temperament:
          "Curious, Intelligent, Loyal, Sweet, Agile, Playful, Affectionate",
        origin: "Russia",
        country_codes: "RU",
        country_code: "RU",
        description:
          "The Siberians dog like temperament and affection makes the ideal lap cat and will live quite happily indoors. Very agile and powerful, the Siberian cat can easily leap and reach high places, including the tops of refrigerators and even doors. ",
        life_span: "12 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Moscow Semi-longhair, HairSiberian Forest Cat",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 2,
        health_issues: 2,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Siberian_(cat)",
        hypoallergenic: 1,
        reference_image_id: "3bkZAjRh1",
      },
    ],
    id: "FUJOW3SIi",
    url: "https://cdn2.thecatapi.com/images/FUJOW3SIi.jpg",
    width: 3060,
    height: 1722,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "7 - 15",
          metric: "3 - 7",
        },
        id: "toyg",
        name: "Toyger",
        vetstreet_url: "http://www.vetstreet.com/cats/toyger",
        temperament: "Playful, Social, Intelligent",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "The Toyger has a sweet, calm personality and is generally friendly. He's outgoing enough to walk on a leash, energetic enough to play fetch and other interactive games, and confident enough to get along with other cats and friendly dogs.",
        life_span: "12 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 2,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 5,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Toyger",
        hypoallergenic: 0,
        reference_image_id: "O3F3_S1XN",
      },
    ],
    id: "Zi4jfH3c6",
    url: "https://cdn2.thecatapi.com/images/Zi4jfH3c6.jpg",
    width: 1080,
    height: 984,
  },
];
export default catData;
